apiVersion : apps/v1
kind: Deployment
metadata:
  name: "deployment-{{ .Values.appName }}"
  labels:
    app.project.name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }} 
    spec:
      containers:
        - name: {{ .Values.appName }} 
          image: {{ .Values.image.name }}
          ports:
            - containerPort: {{ .Values.appPort }}
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /hc
              port: {{ .Values.appPort }}
              scheme: HTTP
            timeoutSeconds: 30
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /hc
              port: {{ .Values.appPort }}
              scheme: HTTP
            timeoutSeconds: 30
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3   
      imagePullSecrets:
        - name: dockerhub           