apiVersion: v1
kind: Service
metadata:
    name: "service-{{ .Values.appName }}"
    labels:
      app.project.name: {{ .Values.appName }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.nodePort }}
      port: {{ .Values.appPort }}
      protocol: TCP
      targetPort: {{ .Values.appPort }}
  selector:
    app: {{ .Values.appName }}